import type { Metadata } from "next";
import "@/app/globals.css";
import ContentLayout from "./contentslayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContentsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
       <div className="flex h-full flex-col ">
         <ContentLayout/>
        <div className="flex-grow ">
            {children}
        </div>
    </div>
      
    
  );
}