import type { Metadata } from "next";
import "@/app/globals.css";
import AdminSideNav from '@/app/ui/sidenavadmin'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className=' min-h-screen'>
       <div className="flex h-full flex-col md:flex-row mt-4">
        <div className="w-full flex-none md:w-64">
            <AdminSideNav />
        </div>
      <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
        {children}
        </div>
    </div>
      </body>
    </html>
  );
}
