import type { Metadata } from "next";
import "@/app/globals.css";
import Header from './ui/header'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className=' min-h-screen'>
        <Header />
        {children}
        <footer className="mt-18 bg-black flex flex-col sm:flex-row sm:justify-around justify-center gap-8 py-10 px-5 w-full">
        <div className="flex justify-center  sm:order-2 ">
          <img src="/favicon.ico" alt="Logo" className="w-20 h-20"/>
        </div>
        <div className="flex flex-col sm:order-1">
           <h1 className="font-bold mb-5">Follow Us</h1>
           <h1 className="">facebook</h1>
           <h1 className="">instagram</h1>
           <h1 className="">twitter</h1>
        </div>
        <div className="flex flex-col justify-center sm:order-3">
          <h1 className="font-bold mb-5">Contact Us</h1>
          <h1 className="">bookfinder@gmail.com</h1>
          <h1 className="">Adiss Abeba, 4kilo</h1>
          <h1 className="">bookfinder | 2025.copyright</h1>
        </div>
      </footer>
      </body>
    </html>
  );
}
