import type { Metadata } from "next";
import "@/app/globals.css";
import BookLayout from "./bookslayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BooksLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-full flex-col ">
      <BookLayout />
      <div className="flex-grow ">{children}</div>
    </div>
  );
}
