import type { Metadata } from "next";
import "@/app/globals.css";
import BooksLayout from "./bookslayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
       <div className="flex h-full flex-col  border">
         <BooksLayout/>
        <div className="flex-grow ">
            {children}
        </div>
    </div>
      
    
  );
}