import type { Metadata } from "next";
import "@/app/globals.css";
import ReviewLayout from "./reviewlayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ReviewsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
       <div className="flex h-screen flex-col  ">
         <ReviewLayout/>
        <div className="flex-grow ">
            {children}
        </div>
    </div>
      
    
  );
}